version: "3"
services:

  mymongo:
    image: "mongo"
    ports:
      - "27017:27017"

  nodebackend:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mymongo
    environment:
      - DB=mongodb://mymongo:27017/crio-stage-2

  reactimage:
    image: "reactimage"
    ports:
      - "3000:3000"
    depends_on:
      - nodebackend